- name: Copies network manger and watchdog
  copy:
    owner: root
    group: root
    mode: 0755
    src: "{{ item }}"
    dest: "/usr/sbin/{{ item }}"
  with_items:
    - screenly_net_mgr.py
    - screenly_net_watchdog.py

- name: Copies network manger init file
  copy:
    owner: root
    group: root
    mode: 0755
    src: screenly_net_mgr
    dest: /etc/init.d/screenly_net_mgr

- name: Copies in sample network.ini file
  copy:
    owner: root
    group: root
    mode: 0644
    src: network.ini-sample
    dest: /boot/network.ini-sample

- name: Activate network manager
  command: update-rc.d screenly_net_mgr defaults

- name: Install cronjob for watchdog
  cron:
    name: Screenly Net Watchdog
    minute: 0
    job: /usr/bin/python /usr/sbin/screenly_net_watchdog.py
